// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDofNFRb-c4BBZC8o7BX8FsK3NYTmuvFl0',
    appId: '1:1044377949427:web:8241f6519b7076835a5386',
    messagingSenderId: '1044377949427',
    projectId: 'fir-d-app-951ca',
    authDomain: 'fir-d-app-951ca.firebaseapp.com',
    storageBucket: 'fir-d-app-951ca.firebasestorage.app',
    measurementId: 'G-V0P3VVFW7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhXJNplDq9QELXcZjpPQ_rxe2QlN_dvHw',
    appId: '1:1044377949427:android:eeee64dbc6cebded5a5386',
    messagingSenderId: '1044377949427',
    projectId: 'fir-d-app-951ca',
    storageBucket: 'fir-d-app-951ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGPSjROS2GWdU6swZf_xGZgb7xRFPTYy8',
    appId: '1:1044377949427:ios:c5afe6f2e2901f515a5386',
    messagingSenderId: '1044377949427',
    projectId: 'fir-d-app-951ca',
    storageBucket: 'fir-d-app-951ca.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );
}
